In [42]:
import pandas as pd
import numpy as np
!pip install pymysql
!pip install sqlalchemy
from sqlalchemy import create_engine
print('Libraries imported correctly')

Requirement already satisfied: pymysql in c:\users\hp\anaconda3\lib\site-packages (1.1.2)

[notice] A new release of pip is available: 25.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: sqlalchemy in c:\users\hp\anaconda3\lib\site-packages (2.0.34)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\hp\anaconda3\lib\site-packages (from sqlalchemy) (4.13.2)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\hp\anaconda3\lib\site-packages (from sqlalchemy) (3.0.1)
Libraries imported correctly

[notice] A new release of pip is available: 25.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [43]:
#insert data
df=pd.read_csv('Adidas_Data.csv')
df.head()

,Retailer,Retailer ID,Invoice Date,Region,State,City,Product,Price per Unit,Units Sold,Total Sales,Operating Profit,Operating Margin,Sales Method
0,Foot Locker,1185732,1/1/2020,Northeast,New York,New York,Men's Street Footwear,$50.00,"1,200","$600,000","$300,000",50%,In-store
1,Foot Locker,1185732,1/2/2020,Northeast,New York,New York,Men's Athletic Footwear,$50.00,"1,000","$500,000","$150,000",30%,In-store
2,Foot Locker,1185732,1/3/2020,Northeast,New York,New York,Women's Street Footwear,$40.00,"1,000","$400,000","$140,000",35%,In-store
3,Foot Locker,1185732,1/4/2020,Northeast,New York,New York,Women's Athletic Footwear,$45.00,850,"$382,500","$133,875",35%,In-store
4,Foot Locker,1185732,1/5/2020,Northeast,New York,New York,Men's Apparel,$60.00,900,"$540,000","$162,000",30%,In-store

In [44]:
#understand data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9648 entries, 0 to 9647
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Retailer          9648 non-null   object
 1   Retailer ID       9648 non-null   int64
 2   Invoice Date      9648 non-null   object
 3   Region            9648 non-null   object
 4   State             9648 non-null   object
 5   City              9648 non-null   object
 6   Product           9648 non-null   object
 7   Price per Unit    9648 non-null   object
 8   Units Sold        9648 non-null   object
 9   Total Sales       9648 non-null   object
 10  Operating Profit  9648 non-null   object
 11  Operating Margin  9648 non-null   object
 12  Sales Method      9648 non-null   object
dtypes: int64(1), object(12)
memory usage: 980.0+ KB

In [45]:
df.describe(include ='all')

,Retailer,Retailer ID,Invoice Date,Region,State,City,Product,Price per Unit,Units Sold,Total Sales,Operating Profit,Operating Margin,Sales Method
count,9648,9.648000e+03,9648,9648,9648,9648,9648,9648,9648,9648,9648,9648,9648
unique,6,NaN,724,5,50,52,6,94,361,3138,4187,66,3
top,Foot Locker,NaN,1/17/2021,West,California,Portland,Men's Street Footwear,$50.00,225,"$100,000","$105,000",35%,Online
freq,2637,NaN,77,2448,432,360,1610,675,207,67,39,1309,4889
mean,NaN,1.173850e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,2.636038e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,1.128299e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,1.185732e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,1.185732e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,1.185732e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,1.197831e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [46]:
df.columns

Index(['Retailer', 'Retailer ID', 'Invoice Date', 'Region', 'State', 'City',
       'Product', 'Price per Unit', 'Units Sold', 'Total Sales',
       'Operating Profit', 'Operating Margin', 'Sales Method'],
      dtype='object')

In [47]:
df.shape

(9648, 13)

In [48]:
df.dtypes

Retailer            object
Retailer ID          int64
Invoice Date        object
Region              object
State               object
City                object
Product             object
Price per Unit      object
Units Sold          object
Total Sales         object
Operating Profit    object
Operating Margin    object
Sales Method        object
dtype: object

In [49]:
df.sample(5)

,Retailer,Retailer ID,Invoice Date,Region,State,City,Product,Price per Unit,Units Sold,Total Sales,Operating Profit,Operating Margin,Sales Method
4173,Foot Locker,1185732,6/1/2021,West,California,Los Angeles,Men's Athletic Footwear,$41.00,77,"$3,157","$1,452",46%,Online
4804,Kohl's,1189833,2/22/2021,Midwest,Montana,Billings,Women's Street Footwear,$41.00,116,"$4,756","$2,711",57%,Online
4250,Sports Direct,1197831,8/17/2021,South,Texas,Dallas,Men's Street Footwear,$23.00,176,"$4,048","$1,741",43%,Online
6500,Foot Locker,1185732,5/16/2021,South,Mississippi,Jackson,Women's Apparel,$47.00,140,"$6,580","$4,211",64%,Online
5038,Amazon,1185732,10/14/2021,South,Alabama,Birmingham,Women's Street Footwear,$28.00,63,"$1,764",$917,52%,Online

In [50]:
#cleaning of the data
#check null values
df.isna().sum()

Retailer            0
Retailer ID         0
Invoice Date        0
Region              0
State               0
City                0
Product             0
Price per Unit      0
Units Sold          0
Total Sales         0
Operating Profit    0
Operating Margin    0
Sales Method        0
dtype: int64

In [51]:
#handle the null values 
#for retailer fill with Not Provided or Unkwon
#handle all the strings columns null values by filling with unknown
strings=[
    'Retailer',
    'Region',
    'State',
    'City',
    'Product',
    'Sales Method'
]

df[strings].fillna('Unknown',inplace=True)

C:\Users\hp\AppData\Local\Temp\ipykernel_9588\57147238.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[strings].fillna('Unknown',inplace=True)

In [52]:
#handle the date column
#check the data type of the date column
df['Invoice Date'].dtype

dtype('O')

In [53]:
#check for dates missing values
df['Invoice Date'].isna().sum()

0

In [54]:
#look for unique entries
df['Invoice Date'].unique()

array(['1/1/2020', '1/2/2020', '1/3/2020', '1/4/2020', '1/5/2020',
       '1/6/2020', '1/7/2020', '1/8/2020', '1/21/2020', '1/22/2020',
       '1/23/2020', '1/24/2020', '1/25/2020', '1/26/2020', '1/27/2020',
       '1/28/2020', '1/29/2020', '1/30/2020', '1/31/2020', '2/1/2020',
       '2/2/2020', '2/3/2020', '2/4/2020', '2/5/2020', '2/6/2020',
       '2/7/2020', '2/8/2020', '2/9/2020', '2/10/2020', '3/3/2020',
       '3/4/2020', '3/5/2020', '3/6/2020', '3/7/2020', '3/8/2020',
       '3/9/2020', '3/10/2020', '3/11/2020', '3/12/2020', '3/13/2020',
       '3/14/2020', '3/15/2020', '3/16/2020', '3/17/2020', '3/18/2020',
       '3/31/2020', '4/17/2020', '4/18/2020', '4/19/2020', '4/20/2020',
       '4/21/2020', '4/22/2020', '4/23/2020', '4/24/2020', '4/25/2020',
       '4/26/2020', '4/27/2020', '4/28/2020', '4/29/2020', '4/30/2020',
       '5/1/2020', '5/2/2020', '5/3/2020', '5/4/2020', '5/5/2020',
       '5/6/2020', '5/7/2020', '7/18/2020', '7/19/2020', '7/20/2020',
       '7/21/2020', '7/22/2020', '7/23/2020', '7/24/2020', '7/25/2020',
       '7/26/2020', '7/27/2020', '7/28/2020', '7/29/2020', '7/30/2020',
       '7/31/2020', '8/1/2020', '8/2/2020', '8/3/2020', '8/4/2020',
       '8/5/2020', '8/6/2020', '8/7/2020', '8/8/2020', '8/9/2020',
       '8/10/2020', '8/11/2020', '8/12/2020', '8/13/2020', '8/14/2020',
       '8/15/2020', '8/16/2020', '8/17/2020', '8/18/2020', '8/19/2020',
       '8/20/2020', '8/21/2020', '8/22/2020', '8/23/2020', '8/24/2020',
       '8/25/2020', '8/26/2020', '8/27/2020', '8/28/2020', '8/29/2020',
       '8/30/2020', '8/31/2020', '9/1/2020', '9/2/2020', '9/3/2020',
       '9/4/2020', '9/5/2020', '9/6/2020', '9/7/2020', '9/8/2020',
       '9/9/2020', '9/10/2020', '9/11/2020', '9/12/2020', '9/13/2020',
       '9/14/2020', '9/15/2020', '9/16/2020', '10/20/2020', '10/21/2020',
       '10/22/2020', '10/23/2020', '10/24/2020', '10/25/2020',
       '10/26/2020', '10/27/2020', '10/28/2020', '10/29/2020',
       '10/30/2020', '10/31/2020', '11/1/2020', '11/2/2020', '11/3/2020',
       '11/4/2020', '11/5/2020', '11/6/2020', '11/7/2020', '11/8/2020',
       '11/9/2020', '11/10/2020', '11/11/2020', '11/12/2020',
       '11/13/2020', '11/14/2020', '11/15/2020', '12/22/2020',
       '12/23/2020', '12/24/2020', '12/25/2020', '12/26/2020',
       '12/27/2020', '12/28/2020', '12/29/2020', '12/30/2020',
       '12/31/2020', '1/1/2021', '1/2/2021', '1/3/2021', '1/4/2021',
       '1/5/2021', '1/6/2021', '1/7/2021', '1/8/2021', '1/9/2021',
       '1/10/2021', '1/11/2021', '1/12/2021', '1/13/2021', '1/14/2021',
       '1/15/2021', '1/16/2021', '1/17/2021', '1/18/2021', '1/19/2021',
       '1/20/2021', '1/21/2021', '1/22/2021', '1/23/2021', '1/24/2021',
       '1/25/2021', '1/26/2021', '1/27/2021', '1/28/2021', '1/29/2021',
       '1/30/2021', '1/31/2021', '2/1/2021', '2/2/2021', '2/3/2021',
       '2/4/2021', '2/5/2021', '2/6/2021', '2/7/2021', '2/8/2021',
       '2/9/2021', '2/10/2021', '2/11/2021', '2/12/2021', '2/13/2021',
       '2/14/2021', '2/15/2021', '2/16/2021', '2/17/2021', '2/18/2021',
       '3/9/2021', '3/10/2021', '3/11/2021', '3/12/2021', '3/13/2021',
       '3/14/2021', '3/15/2021', '3/16/2021', '3/17/2021', '3/18/2021',
       '3/19/2021', '3/20/2021', '3/21/2021', '3/22/2021', '3/23/2021',
       '4/6/2021', '4/7/2021', '4/8/2021', '4/9/2021', '4/10/2021',
       '4/11/2021', '4/12/2021', '4/13/2021', '4/14/2021', '4/15/2021',
       '4/16/2021', '4/17/2021', '4/18/2021', '4/19/2021', '4/20/2021',
       '4/21/2021', '4/22/2021', '4/23/2021', '4/24/2021', '4/25/2021',
       '4/26/2021', '4/27/2021', '4/28/2021', '4/29/2021', '4/30/2021',
       '5/1/2021', '5/2/2021', '5/3/2021', '5/4/2021', '5/5/2021',
       '5/6/2021', '5/7/2021', '5/8/2021', '5/9/2021', '5/10/2021',
       '5/11/2021', '5/12/2021', '5/13/2021', '5/14/2021', '5/15/2021',
       '5/16/2021', '5/17/2021', '5/18/2021', '5/19/2021', '5/20/2021',
       '5/21/2021', '5/22/2021', '5/23/2021', '5/24/2021', '5/25/2021',
       '5/26/2021', '5/27/2021', '5/28/2021', '5/29/2021', '5/30/2021',
       '5/31/2021', '6/1/2021', '6/2/2021', '6/3/2021', '6/4/2021',
       '6/5/2021', '6/6/2021', '6/7/2021', '6/8/2021', '6/9/2021',
       '6/10/2021', '6/11/2021', '6/12/2021', '6/13/2021', '6/14/2021',
       '6/15/2021', '6/16/2021', '6/17/2021', '6/18/2021', '6/19/2021',
       '6/20/2021', '6/21/2021', '6/22/2021', '6/23/2021', '6/24/2021',
       '6/25/2021', '6/26/2021', '6/27/2021', '6/28/2021', '6/29/2021',
       '6/30/2021', '7/1/2021', '7/2/2021', '7/3/2021', '7/4/2021',
       '7/5/2021', '7/6/2021', '7/7/2021', '7/8/2021', '7/9/2021',
       '7/10/2021', '7/11/2021', '7/12/2021', '7/13/2021', '7/14/2021',
       '7/15/2021', '7/16/2021', '7/17/2021', '7/18/2021', '7/19/2021',
       '7/20/2021', '7/21/2021', '7/22/2021', '7/23/2021', '7/24/2021',
       '7/25/2021', '7/26/2021', '7/27/2021', '7/28/2021', '7/29/2021',
       '7/30/2021', '7/31/2021', '8/1/2021', '8/2/2021', '8/3/2021',
       '8/4/2021', '8/5/2021', '8/6/2021', '8/7/2021', '8/8/2021',
       '8/9/2021', '8/10/2021', '8/11/2021', '8/12/2021', '8/13/2021',
       '8/14/2021', '8/15/2021', '8/16/2021', '8/17/2021', '8/18/2021',
       '8/19/2021', '8/20/2021', '8/21/2021', '8/22/2021', '8/23/2021',
       '8/24/2021', '8/25/2021', '8/26/2021', '8/27/2021', '8/28/2021',
       '8/29/2021', '8/30/2021', '8/31/2021', '9/1/2021', '9/2/2021',
       '9/3/2021', '9/4/2021', '9/5/2021', '9/6/2021', '9/7/2021',
       '9/8/2021', '9/9/2021', '9/10/2021', '9/11/2021', '9/12/2021',
       '9/13/2021', '9/14/2021', '9/15/2021', '9/16/2021', '9/17/2021',
       '9/18/2021', '9/19/2021', '9/20/2021', '9/21/2021', '9/22/2021',
       '9/23/2021', '9/24/2021', '9/25/2021', '9/26/2021', '9/27/2021',
       '9/28/2021', '9/29/2021', '9/30/2021', '10/1/2021', '10/2/2021',
       '10/3/2021', '10/4/2021', '10/5/2021', '10/6/2021', '10/7/2021',
       '10/8/2021', '10/9/2021', '10/10/2021', '10/11/2021', '10/12/2021',
       '10/13/2021', '10/14/2021', '10/15/2021', '10/16/2021',
       '10/17/2021', '10/18/2021', '10/19/2021', '10/20/2021',
       '10/21/2021', '10/22/2021', '10/23/2021', '10/24/2021',
       '10/25/2021', '10/26/2021', '10/27/2021', '10/28/2021',
       '10/29/2021', '10/30/2021', '10/31/2021', '11/1/2021', '11/2/2021',
       '11/3/2021', '11/4/2021', '11/5/2021', '11/6/2021', '11/7/2021',
       '11/8/2021', '11/9/2021', '11/10/2021', '11/11/2021', '11/12/2021',
       '11/13/2021', '11/14/2021', '11/15/2021', '11/16/2021',
       '11/17/2021', '11/18/2021', '11/19/2021', '11/20/2021',
       '11/21/2021', '11/22/2021', '11/23/2021', '11/24/2021',
       '11/25/2021', '11/26/2021', '11/27/2021', '11/28/2021',
       '11/29/2021', '11/30/2021', '12/1/2021', '12/2/2021', '12/3/2021',
       '12/4/2021', '12/5/2021', '12/6/2021', '12/7/2021', '12/8/2021',
       '12/9/2021', '12/10/2021', '12/11/2021', '12/12/2021',
       '12/13/2021', '12/14/2021', '12/15/2021', '12/16/2021',
       '12/17/2021', '12/18/2021', '12/19/2021', '12/20/2021',
       '12/21/2021', '12/22/2021', '12/23/2021', '12/24/2021',
       '12/25/2021', '12/26/2021', '12/27/2021', '12/28/2021',
       '12/29/2021', '12/30/2021', '12/31/2021', '1/9/2020', '1/10/2020',
       '1/11/2020', '1/12/2020', '1/13/2020', '1/14/2020', '1/15/2020',
       '1/16/2020', '1/17/2020', '1/18/2020', '1/19/2020', '1/20/2020',
       '2/11/2020', '2/12/2020', '2/13/2020', '2/14/2020', '2/15/2020',
       '2/16/2020', '2/17/2020', '2/18/2020', '2/19/2020', '2/20/2020',
       '2/21/2020', '2/22/2020', '2/23/2020', '2/24/2020', '2/25/2020',
       '2/26/2020', '2/27/2020', '2/28/2020', '3/1/2020', '3/2/2020',
       '3/19/2020', '3/20/2020', '3/21/2020', '3/22/2020', '3/23/2020',
       '3/24/2020', '3/25/2020', '3/26/2020', '3/27/2020', '3/28/2020',
       '3/29/2020', '3/30/2020', '4/1/2020', '4/2/2020', '4/3/2020',
       '4/4/2020', '4/5/2020', '4/6/2020', '4/7/2020', '4/8/2020',
       '4/9/2020', '4/10/2020', '4/11/2020', '4/12/2020', '4/13/2020',
       '4/14/2020', '4/15/2020', '4/16/2020', '5/8/2020', '5/9/2020',
       '5/10/2020', '5/11/2020', '5/12/2020', '5/13/2020', '5/14/2020',
       '5/15/2020', '5/16/2020', '5/17/2020', '5/18/2020', '5/19/2020',
       '5/20/2020', '5/21/2020', '5/22/2020', '5/23/2020', '5/24/2020',
       '5/25/2020', '5/26/2020', '5/27/2020', '5/28/2020', '5/29/2020',
       '5/30/2020', '5/31/2020', '6/1/2020', '6/2/2020', '6/3/2020',
       '6/4/2020', '6/5/2020', '6/6/2020', '6/7/2020', '6/8/2020',
       '6/9/2020', '6/10/2020', '6/11/2020', '6/12/2020', '6/13/2020',
       '6/14/2020', '6/15/2020', '6/16/2020', '6/17/2020', '6/18/2020',
       '6/19/2020', '6/20/2020', '6/21/2020', '6/22/2020', '6/23/2020',
       '6/24/2020', '6/25/2020', '6/26/2020', '6/27/2020', '6/28/2020',
       '6/29/2020', '6/30/2020', '7/1/2020', '7/2/2020', '7/3/2020',
       '7/4/2020', '7/5/2020', '7/6/2020', '7/7/2020', '7/8/2020',
       '7/9/2020', '7/10/2020', '7/11/2020', '7/12/2020', '7/13/2020',
       '7/14/2020', '7/15/2020', '7/16/2020', '7/17/2020', '9/17/2020',
       '9/18/2020', '9/19/2020', '9/20/2020', '9/21/2020', '9/22/2020',
       '9/23/2020', '9/24/2020', '9/25/2020', '9/26/2020', '9/27/2020',
       '9/28/2020', '9/29/2020', '9/30/2020', '10/1/2020', '10/2/2020',
       '10/3/2020', '10/4/2020', '10/5/2020', '10/6/2020', '10/7/2020',
       '10/8/2020', '10/9/2020', '10/10/2020', '10/17/2020', '10/18/2020',
       '10/19/2020', '11/16/2020', '11/17/2020', '11/18/2020',
       '11/19/2020', '11/20/2020', '11/21/2020', '11/22/2020',
       '11/23/2020', '11/24/2020', '11/25/2020', '11/26/2020',
       '11/27/2020', '11/28/2020', '11/29/2020', '11/30/2020',
       '12/1/2020', '12/2/2020', '12/3/2020', '12/4/2020', '12/5/2020',
       '12/6/2020', '12/7/2020', '12/8/2020', '12/9/2020', '12/10/2020',
       '12/11/2020', '12/12/2020', '12/13/2020', '12/14/2020',
       '12/15/2020', '12/16/2020', '12/17/2020', '12/18/2020',
       '12/19/2020', '12/20/2020', '12/21/2020', '2/19/2021', '2/20/2021',
       '2/21/2021', '2/22/2021', '2/23/2021', '2/24/2021', '2/25/2021',
       '2/26/2021', '2/27/2021', '2/28/2021', '3/1/2021', '3/2/2021',
       '3/3/2021', '3/4/2021', '3/5/2021', '3/6/2021', '3/7/2021',
       '3/8/2021', '3/24/2021', '3/25/2021', '3/26/2021', '3/27/2021',
       '3/28/2021', '3/29/2021', '3/30/2021', '3/31/2021', '4/1/2021',
       '4/2/2021', '4/3/2021', '4/4/2021', '4/5/2021'], dtype=object)

In [55]:
#cleaning the date column
#removing the white space
df['Invoice Date']=df['Invoice Date'].str.strip()

In [56]:
#make uniform the null values
df['Invoice Date'].replace(
    ['Unkwon','N/A','','Not Available'],
    pd.NA,
    inplace=True
)

C:\Users\hp\AppData\Local\Temp\ipykernel_9588\1281828328.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Invoice Date'].replace(

In [57]:
#converting to datetime 
df['Invoice Date']=pd.to_datetime(
    df['Invoice Date'],
    errors='coerce'
)

In [58]:
#check failed dates
df[df['Invoice Date'].isna()]

Empty DataFrame
Columns: [Retailer, Retailer ID, Invoice Date, Region, State, City, Product, Price per Unit, Units Sold, Total Sales, Operating Profit, Operating Margin, Sales Method]
Index: []

In [59]:
df['Invoice Date'].dtype

dtype('<M8[ns]')

In [60]:
#extracting required components
df['Year_Num']=df['Invoice Date'].dt.year
df['Month_Num']=df['Invoice Date'].dt.month
df['Month_Name']=df['Invoice Date'].dt.month_name()
df['Day_Num']=df['Invoice Date'].dt.day
df['Day_Name']=df['Invoice Date'].dt.day_name()

In [61]:
#HANDLING currency/numeric columns columns (Price per Unit,Units Sold,Total Sales,Operating Profit,Operating Margin)
#check the data type for the column
currency_columns = [
    'Total Sales',
    'Operating Profit',
    'Price per Unit',
    'Units Sold'
]

In [62]:
#check the data types
df[currency_columns].dtypes

Total Sales         object
Operating Profit    object
Price per Unit      object
Units Sold          object
dtype: object

In [63]:
#check the missing values
df[currency_columns].isna().sum()

Total Sales         0
Operating Profit    0
Price per Unit      0
Units Sold          0
dtype: int64

In [64]:
#remove leading and trailing spaces
for col in currency_columns:
    df[col] = df[col].str.strip()

In [65]:
#replace invalid entries
for col in currency_columns:
    df[col] = df[col].replace(
        ['Unknown', 'N/A', '', '-'],
        pd.NA
    )

In [66]:
#remove currency symbols
for col in currency_columns:
    df[col] = df[col].str.replace('$', '', regex=False)
    df[col] = df[col].str.replace('KES', '', regex=False)
    df[col] = df[col].str.replace('USD', '', regex=False)
    df[col] = df[col].str.replace('€', '', regex=False)
    df[col] = df[col].str.replace('£', '', regex=False)

In [67]:
#remove commas
for col in currency_columns:
    df[col] = df[col].str.replace(',', '', regex=False)

In [68]:
#convert every column to numeric
for col in currency_columns:
    df[col] = pd.to_numeric(
        df[col],
        errors='coerce'
    )

In [69]:
df[currency_columns].dtypes

Total Sales           int64
Operating Profit      int64
Price per Unit      float64
Units Sold            int64
dtype: object

In [70]:
#check the data that we are working with
df[currency_columns].head()

   Total Sales  Operating Profit  Price per Unit  Units Sold
0       600000            300000            50.0        1200
1       500000            150000            50.0        1000
2       400000            140000            40.0        1000
3       382500            133875            45.0         850
4       540000            162000            60.0         900

In [71]:
#handling the % columns
df['Operating Margin'].head

<bound method NDFrame.head of 0       50%
1       30%
2       35%
3       35%
4       30%
       ...
9643    28%
9644    32%
9645    37%
9646    42%
9647    27%
Name: Operating Margin, Length: 9648, dtype: object>

In [72]:
#check the data types
df['Operating Margin'].dtype

dtype('O')

In [73]:
#removing the % symbol
df['Operating Margin'] = df['Operating Margin'].str.replace('%', '', regex=False)

In [74]:
#converting to numeric values
df['Operating Margin'] = pd.to_numeric(
        df['Operating Margin'],
        errors='coerce'
    )

In [75]:
#converting to decimal form
df['Operating Margin']=df['Operating Margin']/100

In [76]:
#cleaning the column names
df.columns=(
    df.columns
    .str.strip()
    .str.replace(' ','_')
    .str.title()
)

In [77]:
df.head()

,Retailer,Retailer_Id,Invoice_Date,Region,State,City,Product,Price_Per_Unit,Units_Sold,Total_Sales,Operating_Profit,Operating_Margin,Sales_Method,Year_Num,Month_Num,Month_Name,Day_Num,Day_Name
0,Foot Locker,1185732,2020-01-01,Northeast,New York,New York,Men's Street Footwear,50.0,1200,600000,300000,0.50,In-store,2020,1,January,1,Wednesday
1,Foot Locker,1185732,2020-01-02,Northeast,New York,New York,Men's Athletic Footwear,50.0,1000,500000,150000,0.30,In-store,2020,1,January,2,Thursday
2,Foot Locker,1185732,2020-01-03,Northeast,New York,New York,Women's Street Footwear,40.0,1000,400000,140000,0.35,In-store,2020,1,January,3,Friday
3,Foot Locker,1185732,2020-01-04,Northeast,New York,New York,Women's Athletic Footwear,45.0,850,382500,133875,0.35,In-store,2020,1,January,4,Saturday
4,Foot Locker,1185732,2020-01-05,Northeast,New York,New York,Men's Apparel,60.0,900,540000,162000,0.30,In-store,2020,1,January,5,Sunday

In [78]:
#check duplicates
df.duplicated().sum()

0

In [79]:
#saving the data
df.to_csv('Addidas_Cleaned_Data.csv',index=False)

In [80]:
df.columns

Index(['Retailer', 'Retailer_Id', 'Invoice_Date', 'Region', 'State', 'City',
       'Product', 'Price_Per_Unit', 'Units_Sold', 'Total_Sales',
       'Operating_Profit', 'Operating_Margin', 'Sales_Method', 'Year_Num',
       'Month_Num', 'Month_Name', 'Day_Num', 'Day_Name'],
      dtype='object')

In [81]:
#creating engine
engine=create_engine(
    "mysql+pymysql://root:Terere#123@localhost/adidas_analytics"
)

In [82]:
# Send DataFrame to MySQL
df.to_sql(
    name="adidas_analytics_table",
    con=engine,
    if_exists="replace",
    index=False
)

print("Data imported successfully!")

Data imported successfully!